// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/action/action.proto

package action

import (
	light "github.com/dennisschroeder/iot-schemas-proto/proto/v1/light"
	notification "github.com/dennisschroeder/iot-schemas-proto/proto/v1/notification"
	scene "github.com/dennisschroeder/iot-schemas-proto/proto/v1/scene"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action Request (NATS -> Gateway -> MQTT)
type ActionRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetEntity string                 `protobuf:"bytes,2,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"` // e.g., "light.of_desk_sublight"
	// Types that are valid to be assigned to Command:
	//
	//	*ActionRequest_Light
	//	*ActionRequest_Scene
	//	*ActionRequest_Notification
	Command       isActionRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_v1_action_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_action_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_action_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionRequest) GetTargetEntity() string {
	if x != nil {
		return x.TargetEntity
	}
	return ""
}

func (x *ActionRequest) GetCommand() isActionRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ActionRequest) GetLight() *light.LightCommand {
	if x != nil {
		if x, ok := x.Command.(*ActionRequest_Light); ok {
			return x.Light
		}
	}
	return nil
}

func (x *ActionRequest) GetScene() *scene.SceneCommand {
	if x != nil {
		if x, ok := x.Command.(*ActionRequest_Scene); ok {
			return x.Scene
		}
	}
	return nil
}

func (x *ActionRequest) GetNotification() *notification.NotificationCommand {
	if x != nil {
		if x, ok := x.Command.(*ActionRequest_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isActionRequest_Command interface {
	isActionRequest_Command()
}

type ActionRequest_Light struct {
	Light *light.LightCommand `protobuf:"bytes,3,opt,name=light,proto3,oneof"`
}

type ActionRequest_Scene struct {
	Scene *scene.SceneCommand `protobuf:"bytes,4,opt,name=scene,proto3,oneof"`
}

type ActionRequest_Notification struct {
	Notification *notification.NotificationCommand `protobuf:"bytes,5,opt,name=notification,proto3,oneof"`
}

func (*ActionRequest_Light) isActionRequest_Command() {}

func (*ActionRequest_Scene) isActionRequest_Command() {}

func (*ActionRequest_Notification) isActionRequest_Command() {}

var File_proto_v1_action_action_proto protoreflect.FileDescriptor

const file_proto_v1_action_action_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/action/action.proto\x12\riot.v1.action\x1a\x1aproto/v1/light/light.proto\x1a\x1aproto/v1/scene/scene.proto\x1a(proto/v1/notification/notification.proto\"\x87\x02\n" +
	"\rActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtarget_entity\x18\x02 \x01(\tR\ftargetEntity\x122\n" +
	"\x05light\x18\x03 \x01(\v2\x1a.iot.v1.light.LightCommandH\x00R\x05light\x122\n" +
	"\x05scene\x18\x04 \x01(\v2\x1a.iot.v1.scene.SceneCommandH\x00R\x05scene\x12N\n" +
	"\fnotification\x18\x05 \x01(\v2(.iot.v1.notification.NotificationCommandH\x00R\fnotificationB\t\n" +
	"\acommandB>Z<github.com/dennisschroeder/iot-schemas-proto/proto/v1/actionb\x06proto3"

var (
	file_proto_v1_action_action_proto_rawDescOnce sync.Once
	file_proto_v1_action_action_proto_rawDescData []byte
)

func file_proto_v1_action_action_proto_rawDescGZIP() []byte {
	file_proto_v1_action_action_proto_rawDescOnce.Do(func() {
		file_proto_v1_action_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_action_action_proto_rawDesc), len(file_proto_v1_action_action_proto_rawDesc)))
	})
	return file_proto_v1_action_action_proto_rawDescData
}

var file_proto_v1_action_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_action_action_proto_goTypes = []any{
	(*ActionRequest)(nil),                    // 0: iot.v1.action.ActionRequest
	(*light.LightCommand)(nil),               // 1: iot.v1.light.LightCommand
	(*scene.SceneCommand)(nil),               // 2: iot.v1.scene.SceneCommand
	(*notification.NotificationCommand)(nil), // 3: iot.v1.notification.NotificationCommand
}
var file_proto_v1_action_action_proto_depIdxs = []int32{
	1, // 0: iot.v1.action.ActionRequest.light:type_name -> iot.v1.light.LightCommand
	2, // 1: iot.v1.action.ActionRequest.scene:type_name -> iot.v1.scene.SceneCommand
	3, // 2: iot.v1.action.ActionRequest.notification:type_name -> iot.v1.notification.NotificationCommand
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_action_action_proto_init() }
func file_proto_v1_action_action_proto_init() {
	if File_proto_v1_action_action_proto != nil {
		return
	}
	file_proto_v1_action_action_proto_msgTypes[0].OneofWrappers = []any{
		(*ActionRequest_Light)(nil),
		(*ActionRequest_Scene)(nil),
		(*ActionRequest_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_action_action_proto_rawDesc), len(file_proto_v1_action_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_action_action_proto_goTypes,
		DependencyIndexes: file_proto_v1_action_action_proto_depIdxs,
		MessageInfos:      file_proto_v1_action_action_proto_msgTypes,
	}.Build()
	File_proto_v1_action_action_proto = out.File
	file_proto_v1_action_action_proto_goTypes = nil
	file_proto_v1_action_action_proto_depIdxs = nil
}
