// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status Enums (Matter/Google Home Style)
type BinaryState int32

const (
	BinaryState_BINARY_STATE_UNSPECIFIED BinaryState = 0
	BinaryState_BINARY_STATE_OFF         BinaryState = 1
	BinaryState_BINARY_STATE_ON          BinaryState = 2
)

// Enum value maps for BinaryState.
var (
	BinaryState_name = map[int32]string{
		0: "BINARY_STATE_UNSPECIFIED",
		1: "BINARY_STATE_OFF",
		2: "BINARY_STATE_ON",
	}
	BinaryState_value = map[string]int32{
		"BINARY_STATE_UNSPECIFIED": 0,
		"BINARY_STATE_OFF":         1,
		"BINARY_STATE_ON":          2,
	}
)

func (x BinaryState) Enum() *BinaryState {
	p := new(BinaryState)
	*p = x
	return p
}

func (x BinaryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_common_proto_enumTypes[0].Descriptor()
}

func (BinaryState) Type() protoreflect.EnumType {
	return &file_proto_v1_common_common_proto_enumTypes[0]
}

func (x BinaryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryState.Descriptor instead.
func (BinaryState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{0}
}

type ColorXY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorXY) Reset() {
	*x = ColorXY{}
	mi := &file_proto_v1_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorXY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorXY) ProtoMessage() {}

func (x *ColorXY) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorXY.ProtoReflect.Descriptor instead.
func (*ColorXY) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *ColorXY) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ColorXY) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_proto_v1_common_common_proto protoreflect.FileDescriptor

const file_proto_v1_common_common_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/common/common.proto\x12\riot.v1.common\"%\n" +
	"\aColorXY\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y*V\n" +
	"\vBinaryState\x12\x1c\n" +
	"\x18BINARY_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BINARY_STATE_OFF\x10\x01\x12\x13\n" +
	"\x0fBINARY_STATE_ON\x10\x02B>Z<github.com/dennisschroeder/iot-schemas-proto/proto/v1/commonb\x06proto3"

var (
	file_proto_v1_common_common_proto_rawDescOnce sync.Once
	file_proto_v1_common_common_proto_rawDescData []byte
)

func file_proto_v1_common_common_proto_rawDescGZIP() []byte {
	file_proto_v1_common_common_proto_rawDescOnce.Do(func() {
		file_proto_v1_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_common_common_proto_rawDesc), len(file_proto_v1_common_common_proto_rawDesc)))
	})
	return file_proto_v1_common_common_proto_rawDescData
}

var file_proto_v1_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_common_common_proto_goTypes = []any{
	(BinaryState)(0), // 0: iot.v1.common.BinaryState
	(*ColorXY)(nil),  // 1: iot.v1.common.ColorXY
}
var file_proto_v1_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_common_common_proto_init() }
func file_proto_v1_common_common_proto_init() {
	if File_proto_v1_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_common_common_proto_rawDesc), len(file_proto_v1_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_common_common_proto_goTypes,
		DependencyIndexes: file_proto_v1_common_common_proto_depIdxs,
		EnumInfos:         file_proto_v1_common_common_proto_enumTypes,
		MessageInfos:      file_proto_v1_common_common_proto_msgTypes,
	}.Build()
	File_proto_v1_common_common_proto = out.File
	file_proto_v1_common_common_proto_goTypes = nil
	file_proto_v1_common_common_proto_depIdxs = nil
}
