// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/envelope/envelope.proto

package envelope

import (
	light "github.com/dennisschroeder/iot-schemas-proto/proto/v1/light"
	presence "github.com/dennisschroeder/iot-schemas-proto/proto/v1/presence"
	sensor "github.com/dennisschroeder/iot-schemas-proto/proto/v1/sensor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event Envelope (ADR 003)
type EventEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // UUID
	Source    string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // z.B. "everything_presence_one"
	Topic     string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`   // Original MQTT Topic
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventEnvelope_Presence
	//	*EventEnvelope_Light
	//	*EventEnvelope_Sensor
	Payload       isEventEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_proto_v1_envelope_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_envelope_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_v1_envelope_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetPayload() isEventEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetPresence() *presence.PresenceEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *EventEnvelope) GetLight() *light.LightEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_Light); ok {
			return x.Light
		}
	}
	return nil
}

func (x *EventEnvelope) GetSensor() *sensor.SensorEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_Sensor); ok {
			return x.Sensor
		}
	}
	return nil
}

type isEventEnvelope_Payload interface {
	isEventEnvelope_Payload()
}

type EventEnvelope_Presence struct {
	Presence *presence.PresenceEvent `protobuf:"bytes,5,opt,name=presence,proto3,oneof"`
}

type EventEnvelope_Light struct {
	Light *light.LightEvent `protobuf:"bytes,6,opt,name=light,proto3,oneof"`
}

type EventEnvelope_Sensor struct {
	Sensor *sensor.SensorEvent `protobuf:"bytes,7,opt,name=sensor,proto3,oneof"`
}

func (*EventEnvelope_Presence) isEventEnvelope_Payload() {}

func (*EventEnvelope_Light) isEventEnvelope_Payload() {}

func (*EventEnvelope_Sensor) isEventEnvelope_Payload() {}

var File_proto_v1_envelope_envelope_proto protoreflect.FileDescriptor

const file_proto_v1_envelope_envelope_proto_rawDesc = "" +
	"\n" +
	" proto/v1/envelope/envelope.proto\x12\x0fiot.v1.envelope\x1a\x1fgoogle/protobuf/timestamp.proto\x1a proto/v1/presence/presence.proto\x1a\x1aproto/v1/light/light.proto\x1a\x1cproto/v1/sensor/sensor.proto\"\xb8\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12<\n" +
	"\bpresence\x18\x05 \x01(\v2\x1e.iot.v1.presence.PresenceEventH\x00R\bpresence\x120\n" +
	"\x05light\x18\x06 \x01(\v2\x18.iot.v1.light.LightEventH\x00R\x05light\x124\n" +
	"\x06sensor\x18\a \x01(\v2\x1a.iot.v1.sensor.SensorEventH\x00R\x06sensorB\t\n" +
	"\apayloadB@Z>github.com/dennisschroeder/iot-schemas-proto/proto/v1/envelopeb\x06proto3"

var (
	file_proto_v1_envelope_envelope_proto_rawDescOnce sync.Once
	file_proto_v1_envelope_envelope_proto_rawDescData []byte
)

func file_proto_v1_envelope_envelope_proto_rawDescGZIP() []byte {
	file_proto_v1_envelope_envelope_proto_rawDescOnce.Do(func() {
		file_proto_v1_envelope_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_envelope_envelope_proto_rawDesc), len(file_proto_v1_envelope_envelope_proto_rawDesc)))
	})
	return file_proto_v1_envelope_envelope_proto_rawDescData
}

var file_proto_v1_envelope_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_envelope_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil),          // 0: iot.v1.envelope.EventEnvelope
	(*timestamppb.Timestamp)(nil),  // 1: google.protobuf.Timestamp
	(*presence.PresenceEvent)(nil), // 2: iot.v1.presence.PresenceEvent
	(*light.LightEvent)(nil),       // 3: iot.v1.light.LightEvent
	(*sensor.SensorEvent)(nil),     // 4: iot.v1.sensor.SensorEvent
}
var file_proto_v1_envelope_envelope_proto_depIdxs = []int32{
	1, // 0: iot.v1.envelope.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: iot.v1.envelope.EventEnvelope.presence:type_name -> iot.v1.presence.PresenceEvent
	3, // 2: iot.v1.envelope.EventEnvelope.light:type_name -> iot.v1.light.LightEvent
	4, // 3: iot.v1.envelope.EventEnvelope.sensor:type_name -> iot.v1.sensor.SensorEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_envelope_envelope_proto_init() }
func file_proto_v1_envelope_envelope_proto_init() {
	if File_proto_v1_envelope_envelope_proto != nil {
		return
	}
	file_proto_v1_envelope_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_Presence)(nil),
		(*EventEnvelope_Light)(nil),
		(*EventEnvelope_Sensor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_envelope_envelope_proto_rawDesc), len(file_proto_v1_envelope_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_envelope_envelope_proto_goTypes,
		DependencyIndexes: file_proto_v1_envelope_envelope_proto_depIdxs,
		MessageInfos:      file_proto_v1_envelope_envelope_proto_msgTypes,
	}.Build()
	File_proto_v1_envelope_envelope_proto = out.File
	file_proto_v1_envelope_envelope_proto_goTypes = nil
	file_proto_v1_envelope_envelope_proto_depIdxs = nil
}
