// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/scene/scene.proto

package scene

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       string                 `protobuf:"bytes,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneCommand) Reset() {
	*x = SceneCommand{}
	mi := &file_proto_v1_scene_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCommand) ProtoMessage() {}

func (x *SceneCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_scene_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCommand.ProtoReflect.Descriptor instead.
func (*SceneCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_scene_scene_proto_rawDescGZIP(), []int{0}
}

func (x *SceneCommand) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

var File_proto_v1_scene_scene_proto protoreflect.FileDescriptor

const file_proto_v1_scene_scene_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/scene/scene.proto\x12\fiot.v1.scene\")\n" +
	"\fSceneCommand\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\tR\asceneIdB=Z;github.com/dennisschroeder/iot-schemas-proto/proto/v1/sceneb\x06proto3"

var (
	file_proto_v1_scene_scene_proto_rawDescOnce sync.Once
	file_proto_v1_scene_scene_proto_rawDescData []byte
)

func file_proto_v1_scene_scene_proto_rawDescGZIP() []byte {
	file_proto_v1_scene_scene_proto_rawDescOnce.Do(func() {
		file_proto_v1_scene_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_scene_scene_proto_rawDesc), len(file_proto_v1_scene_scene_proto_rawDesc)))
	})
	return file_proto_v1_scene_scene_proto_rawDescData
}

var file_proto_v1_scene_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_scene_scene_proto_goTypes = []any{
	(*SceneCommand)(nil), // 0: iot.v1.scene.SceneCommand
}
var file_proto_v1_scene_scene_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_scene_scene_proto_init() }
func file_proto_v1_scene_scene_proto_init() {
	if File_proto_v1_scene_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_scene_scene_proto_rawDesc), len(file_proto_v1_scene_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_scene_scene_proto_goTypes,
		DependencyIndexes: file_proto_v1_scene_scene_proto_depIdxs,
		MessageInfos:      file_proto_v1_scene_scene_proto_msgTypes,
	}.Build()
	File_proto_v1_scene_scene_proto = out.File
	file_proto_v1_scene_scene_proto_goTypes = nil
	file_proto_v1_scene_scene_proto_depIdxs = nil
}
