// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/presence/presence.proto

package presence

import (
	common "github.com/dennisschroeder/iot-schemas-proto/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain: Presence (PIR/Motion)
type PresenceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State         common.BinaryState     `protobuf:"varint,2,opt,name=state,proto3,enum=iot.v1.common.BinaryState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_proto_v1_presence_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_presence_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_presence_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PresenceEvent) GetState() common.BinaryState {
	if x != nil {
		return x.State
	}
	return common.BinaryState(0)
}

var File_proto_v1_presence_presence_proto protoreflect.FileDescriptor

const file_proto_v1_presence_presence_proto_rawDesc = "" +
	"\n" +
	" proto/v1/presence/presence.proto\x12\x0fiot.v1.presence\x1a\x1cproto/v1/common/common.proto\"^\n" +
	"\rPresenceEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.iot.v1.common.BinaryStateR\x05stateB@Z>github.com/dennisschroeder/iot-schemas-proto/proto/v1/presenceb\x06proto3"

var (
	file_proto_v1_presence_presence_proto_rawDescOnce sync.Once
	file_proto_v1_presence_presence_proto_rawDescData []byte
)

func file_proto_v1_presence_presence_proto_rawDescGZIP() []byte {
	file_proto_v1_presence_presence_proto_rawDescOnce.Do(func() {
		file_proto_v1_presence_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_presence_presence_proto_rawDesc), len(file_proto_v1_presence_presence_proto_rawDesc)))
	})
	return file_proto_v1_presence_presence_proto_rawDescData
}

var file_proto_v1_presence_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_presence_presence_proto_goTypes = []any{
	(*PresenceEvent)(nil),   // 0: iot.v1.presence.PresenceEvent
	(common.BinaryState)(0), // 1: iot.v1.common.BinaryState
}
var file_proto_v1_presence_presence_proto_depIdxs = []int32{
	1, // 0: iot.v1.presence.PresenceEvent.state:type_name -> iot.v1.common.BinaryState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_presence_presence_proto_init() }
func file_proto_v1_presence_presence_proto_init() {
	if File_proto_v1_presence_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_presence_presence_proto_rawDesc), len(file_proto_v1_presence_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_presence_presence_proto_goTypes,
		DependencyIndexes: file_proto_v1_presence_presence_proto_depIdxs,
		MessageInfos:      file_proto_v1_presence_presence_proto_msgTypes,
	}.Build()
	File_proto_v1_presence_presence_proto = out.File
	file_proto_v1_presence_presence_proto_goTypes = nil
	file_proto_v1_presence_presence_proto_depIdxs = nil
}
