// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/cover/cover.proto

package cover

import (
	_ "github.com/dennisschroeder/iot-schemas-proto/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain: Cover (Rollläden, Jalousien, Markisen)
type CoverEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`              // "open", "closed", "opening", "closing"
	Position      *int32                 `protobuf:"varint,3,opt,name=position,proto3,oneof" json:"position,omitempty"` // 0-100%
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverEvent) Reset() {
	*x = CoverEvent{}
	mi := &file_proto_v1_cover_cover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverEvent) ProtoMessage() {}

func (x *CoverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cover_cover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverEvent.ProtoReflect.Descriptor instead.
func (*CoverEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_cover_cover_proto_rawDescGZIP(), []int{0}
}

func (x *CoverEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CoverEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CoverEvent) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type CoverCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`              // "OPEN", "CLOSE", "STOP"
	Position      *int32                 `protobuf:"varint,2,opt,name=position,proto3,oneof" json:"position,omitempty"` // 0-100%
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverCommand) Reset() {
	*x = CoverCommand{}
	mi := &file_proto_v1_cover_cover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverCommand) ProtoMessage() {}

func (x *CoverCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cover_cover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverCommand.ProtoReflect.Descriptor instead.
func (*CoverCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_cover_cover_proto_rawDescGZIP(), []int{1}
}

func (x *CoverCommand) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CoverCommand) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

var File_proto_v1_cover_cover_proto protoreflect.FileDescriptor

const file_proto_v1_cover_cover_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/cover/cover.proto\x12\fiot.v1.cover\x1a\x1cproto/v1/common/common.proto\"m\n" +
	"\n" +
	"CoverEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\bposition\x18\x03 \x01(\x05H\x00R\bposition\x88\x01\x01B\v\n" +
	"\t_position\"R\n" +
	"\fCoverCommand\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\bposition\x18\x02 \x01(\x05H\x00R\bposition\x88\x01\x01B\v\n" +
	"\t_positionB=Z;github.com/dennisschroeder/iot-schemas-proto/proto/v1/coverb\x06proto3"

var (
	file_proto_v1_cover_cover_proto_rawDescOnce sync.Once
	file_proto_v1_cover_cover_proto_rawDescData []byte
)

func file_proto_v1_cover_cover_proto_rawDescGZIP() []byte {
	file_proto_v1_cover_cover_proto_rawDescOnce.Do(func() {
		file_proto_v1_cover_cover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_cover_cover_proto_rawDesc), len(file_proto_v1_cover_cover_proto_rawDesc)))
	})
	return file_proto_v1_cover_cover_proto_rawDescData
}

var file_proto_v1_cover_cover_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_cover_cover_proto_goTypes = []any{
	(*CoverEvent)(nil),   // 0: iot.v1.cover.CoverEvent
	(*CoverCommand)(nil), // 1: iot.v1.cover.CoverCommand
}
var file_proto_v1_cover_cover_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_cover_cover_proto_init() }
func file_proto_v1_cover_cover_proto_init() {
	if File_proto_v1_cover_cover_proto != nil {
		return
	}
	file_proto_v1_cover_cover_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_v1_cover_cover_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_cover_cover_proto_rawDesc), len(file_proto_v1_cover_cover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_cover_cover_proto_goTypes,
		DependencyIndexes: file_proto_v1_cover_cover_proto_depIdxs,
		MessageInfos:      file_proto_v1_cover_cover_proto_msgTypes,
	}.Build()
	File_proto_v1_cover_cover_proto = out.File
	file_proto_v1_cover_cover_proto_goTypes = nil
	file_proto_v1_cover_cover_proto_depIdxs = nil
}
