// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationCommand) Reset() {
	*x = NotificationCommand{}
	mi := &file_proto_v1_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCommand) ProtoMessage() {}

func (x *NotificationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCommand.ProtoReflect.Descriptor instead.
func (*NotificationCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationCommand) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationCommand) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationCommand) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_v1_notification_notification_proto protoreflect.FileDescriptor

const file_proto_v1_notification_notification_proto_rawDesc = "" +
	"\n" +
	"(proto/v1/notification/notification.proto\x12\x13iot.v1.notification\"\xc6\x01\n" +
	"\x13NotificationCommand\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x04data\x18\x03 \x03(\v22.iot.v1.notification.NotificationCommand.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BDZBgithub.com/dennisschroeder/iot-schemas-proto/proto/v1/notificationb\x06proto3"

var (
	file_proto_v1_notification_notification_proto_rawDescOnce sync.Once
	file_proto_v1_notification_notification_proto_rawDescData []byte
)

func file_proto_v1_notification_notification_proto_rawDescGZIP() []byte {
	file_proto_v1_notification_notification_proto_rawDescOnce.Do(func() {
		file_proto_v1_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_notification_notification_proto_rawDesc), len(file_proto_v1_notification_notification_proto_rawDesc)))
	})
	return file_proto_v1_notification_notification_proto_rawDescData
}

var file_proto_v1_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_notification_notification_proto_goTypes = []any{
	(*NotificationCommand)(nil), // 0: iot.v1.notification.NotificationCommand
	nil,                         // 1: iot.v1.notification.NotificationCommand.DataEntry
}
var file_proto_v1_notification_notification_proto_depIdxs = []int32{
	1, // 0: iot.v1.notification.NotificationCommand.data:type_name -> iot.v1.notification.NotificationCommand.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_notification_notification_proto_init() }
func file_proto_v1_notification_notification_proto_init() {
	if File_proto_v1_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_notification_notification_proto_rawDesc), len(file_proto_v1_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_notification_notification_proto_goTypes,
		DependencyIndexes: file_proto_v1_notification_notification_proto_depIdxs,
		MessageInfos:      file_proto_v1_notification_notification_proto_msgTypes,
	}.Build()
	File_proto_v1_notification_notification_proto = out.File
	file_proto_v1_notification_notification_proto_goTypes = nil
	file_proto_v1_notification_notification_proto_depIdxs = nil
}
