// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/light/light.proto

package light

import (
	common "github.com/dennisschroeder/iot-schemas-proto/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain: Light
type LightEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State         common.BinaryState     `protobuf:"varint,2,opt,name=state,proto3,enum=iot.v1.common.BinaryState" json:"state,omitempty"`
	Brightness    float32                `protobuf:"fixed32,3,opt,name=brightness,proto3" json:"brightness,omitempty"`                     // 0.0 - 1.0
	ColorTemp     *int32                 `protobuf:"varint,4,opt,name=color_temp,json=colorTemp,proto3,oneof" json:"color_temp,omitempty"` // in Mireds
	Color         *common.ColorXY        `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	ColorMode     *string                `protobuf:"bytes,6,opt,name=color_mode,json=colorMode,proto3,oneof" json:"color_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightEvent) Reset() {
	*x = LightEvent{}
	mi := &file_proto_v1_light_light_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightEvent) ProtoMessage() {}

func (x *LightEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_light_light_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightEvent.ProtoReflect.Descriptor instead.
func (*LightEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_light_light_proto_rawDescGZIP(), []int{0}
}

func (x *LightEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LightEvent) GetState() common.BinaryState {
	if x != nil {
		return x.State
	}
	return common.BinaryState(0)
}

func (x *LightEvent) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *LightEvent) GetColorTemp() int32 {
	if x != nil && x.ColorTemp != nil {
		return *x.ColorTemp
	}
	return 0
}

func (x *LightEvent) GetColor() *common.ColorXY {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *LightEvent) GetColorMode() string {
	if x != nil && x.ColorMode != nil {
		return *x.ColorMode
	}
	return ""
}

type LightCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         common.BinaryState     `protobuf:"varint,1,opt,name=state,proto3,enum=iot.v1.common.BinaryState" json:"state,omitempty"`
	Brightness    float32                `protobuf:"fixed32,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightCommand) Reset() {
	*x = LightCommand{}
	mi := &file_proto_v1_light_light_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightCommand) ProtoMessage() {}

func (x *LightCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_light_light_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightCommand.ProtoReflect.Descriptor instead.
func (*LightCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_light_light_proto_rawDescGZIP(), []int{1}
}

func (x *LightCommand) GetState() common.BinaryState {
	if x != nil {
		return x.State
	}
	return common.BinaryState(0)
}

func (x *LightCommand) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

var File_proto_v1_light_light_proto protoreflect.FileDescriptor

const file_proto_v1_light_light_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/light/light.proto\x12\fiot.v1.light\x1a\x1cproto/v1/common/common.proto\"\x8f\x02\n" +
	"\n" +
	"LightEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.iot.v1.common.BinaryStateR\x05state\x12\x1e\n" +
	"\n" +
	"brightness\x18\x03 \x01(\x02R\n" +
	"brightness\x12\"\n" +
	"\n" +
	"color_temp\x18\x04 \x01(\x05H\x00R\tcolorTemp\x88\x01\x01\x12,\n" +
	"\x05color\x18\x05 \x01(\v2\x16.iot.v1.common.ColorXYR\x05color\x12\"\n" +
	"\n" +
	"color_mode\x18\x06 \x01(\tH\x01R\tcolorMode\x88\x01\x01B\r\n" +
	"\v_color_tempB\r\n" +
	"\v_color_mode\"`\n" +
	"\fLightCommand\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.iot.v1.common.BinaryStateR\x05state\x12\x1e\n" +
	"\n" +
	"brightness\x18\x02 \x01(\x02R\n" +
	"brightnessB=Z;github.com/dennisschroeder/iot-schemas-proto/proto/v1/lightb\x06proto3"

var (
	file_proto_v1_light_light_proto_rawDescOnce sync.Once
	file_proto_v1_light_light_proto_rawDescData []byte
)

func file_proto_v1_light_light_proto_rawDescGZIP() []byte {
	file_proto_v1_light_light_proto_rawDescOnce.Do(func() {
		file_proto_v1_light_light_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_light_light_proto_rawDesc), len(file_proto_v1_light_light_proto_rawDesc)))
	})
	return file_proto_v1_light_light_proto_rawDescData
}

var file_proto_v1_light_light_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_light_light_proto_goTypes = []any{
	(*LightEvent)(nil),      // 0: iot.v1.light.LightEvent
	(*LightCommand)(nil),    // 1: iot.v1.light.LightCommand
	(common.BinaryState)(0), // 2: iot.v1.common.BinaryState
	(*common.ColorXY)(nil),  // 3: iot.v1.common.ColorXY
}
var file_proto_v1_light_light_proto_depIdxs = []int32{
	2, // 0: iot.v1.light.LightEvent.state:type_name -> iot.v1.common.BinaryState
	3, // 1: iot.v1.light.LightEvent.color:type_name -> iot.v1.common.ColorXY
	2, // 2: iot.v1.light.LightCommand.state:type_name -> iot.v1.common.BinaryState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_light_light_proto_init() }
func file_proto_v1_light_light_proto_init() {
	if File_proto_v1_light_light_proto != nil {
		return
	}
	file_proto_v1_light_light_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_light_light_proto_rawDesc), len(file_proto_v1_light_light_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_light_light_proto_goTypes,
		DependencyIndexes: file_proto_v1_light_light_proto_depIdxs,
		MessageInfos:      file_proto_v1_light_light_proto_msgTypes,
	}.Build()
	File_proto_v1_light_light_proto = out.File
	file_proto_v1_light_light_proto_goTypes = nil
	file_proto_v1_light_light_proto_depIdxs = nil
}
