// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/sensor/sensor.proto

package sensor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic Sensor Event (Legacy/Fallback)
type SensorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	NumericValue  float64                `protobuf:"fixed64,5,opt,name=numeric_value,json=numericValue,proto3" json:"numeric_value,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorEvent) Reset() {
	*x = SensorEvent{}
	mi := &file_proto_v1_sensor_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEvent) ProtoMessage() {}

func (x *SensorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_sensor_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEvent.ProtoReflect.Descriptor instead.
func (*SensorEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_sensor_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SensorEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SensorEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SensorEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SensorEvent) GetNumericValue() float64 {
	if x != nil {
		return x.NumericValue
	}
	return 0
}

func (x *SensorEvent) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SensorEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_v1_sensor_sensor_proto protoreflect.FileDescriptor

const file_proto_v1_sensor_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/sensor/sensor.proto\x12\riot.v1.sensor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\vSensorEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12#\n" +
	"\rnumeric_value\x18\x05 \x01(\x01R\fnumericValue\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB>Z<github.com/dennisschroeder/iot-schemas-proto/proto/v1/sensorb\x06proto3"

var (
	file_proto_v1_sensor_sensor_proto_rawDescOnce sync.Once
	file_proto_v1_sensor_sensor_proto_rawDescData []byte
)

func file_proto_v1_sensor_sensor_proto_rawDescGZIP() []byte {
	file_proto_v1_sensor_sensor_proto_rawDescOnce.Do(func() {
		file_proto_v1_sensor_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_sensor_sensor_proto_rawDesc), len(file_proto_v1_sensor_sensor_proto_rawDesc)))
	})
	return file_proto_v1_sensor_sensor_proto_rawDescData
}

var file_proto_v1_sensor_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_sensor_sensor_proto_goTypes = []any{
	(*SensorEvent)(nil),           // 0: iot.v1.sensor.SensorEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_v1_sensor_sensor_proto_depIdxs = []int32{
	1, // 0: iot.v1.sensor.SensorEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_sensor_sensor_proto_init() }
func file_proto_v1_sensor_sensor_proto_init() {
	if File_proto_v1_sensor_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_sensor_sensor_proto_rawDesc), len(file_proto_v1_sensor_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_sensor_sensor_proto_goTypes,
		DependencyIndexes: file_proto_v1_sensor_sensor_proto_depIdxs,
		MessageInfos:      file_proto_v1_sensor_sensor_proto_msgTypes,
	}.Build()
	File_proto_v1_sensor_sensor_proto = out.File
	file_proto_v1_sensor_sensor_proto_goTypes = nil
	file_proto_v1_sensor_sensor_proto_depIdxs = nil
}
