// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/binary_sensor/binary_sensor.proto

package binary_sensor

import (
	common "github.com/dennisschroeder/iot-schemas-proto/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain: Binary Sensor (Motion, Presence, Door, Window, Smoke)
type BinarySensorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	State         common.BinaryState     `protobuf:"varint,2,opt,name=state,proto3,enum=iot.v1.common.BinaryState" json:"state,omitempty"`
	DeviceClass   string                 `protobuf:"bytes,3,opt,name=device_class,json=deviceClass,proto3" json:"device_class,omitempty"` // e.g., "motion", "presence", "door", "window"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinarySensorEvent) Reset() {
	*x = BinarySensorEvent{}
	mi := &file_proto_v1_binary_sensor_binary_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinarySensorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinarySensorEvent) ProtoMessage() {}

func (x *BinarySensorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_binary_sensor_binary_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinarySensorEvent.ProtoReflect.Descriptor instead.
func (*BinarySensorEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_binary_sensor_binary_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *BinarySensorEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *BinarySensorEvent) GetState() common.BinaryState {
	if x != nil {
		return x.State
	}
	return common.BinaryState(0)
}

func (x *BinarySensorEvent) GetDeviceClass() string {
	if x != nil {
		return x.DeviceClass
	}
	return ""
}

var File_proto_v1_binary_sensor_binary_sensor_proto protoreflect.FileDescriptor

const file_proto_v1_binary_sensor_binary_sensor_proto_rawDesc = "" +
	"\n" +
	"*proto/v1/binary_sensor/binary_sensor.proto\x12\x14iot.v1.binary_sensor\x1a\x1cproto/v1/common/common.proto\"\x85\x01\n" +
	"\x11BinarySensorEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.iot.v1.common.BinaryStateR\x05state\x12!\n" +
	"\fdevice_class\x18\x03 \x01(\tR\vdeviceClassBEZCgithub.com/dennisschroeder/iot-schemas-proto/proto/v1/binary_sensorb\x06proto3"

var (
	file_proto_v1_binary_sensor_binary_sensor_proto_rawDescOnce sync.Once
	file_proto_v1_binary_sensor_binary_sensor_proto_rawDescData []byte
)

func file_proto_v1_binary_sensor_binary_sensor_proto_rawDescGZIP() []byte {
	file_proto_v1_binary_sensor_binary_sensor_proto_rawDescOnce.Do(func() {
		file_proto_v1_binary_sensor_binary_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_binary_sensor_binary_sensor_proto_rawDesc), len(file_proto_v1_binary_sensor_binary_sensor_proto_rawDesc)))
	})
	return file_proto_v1_binary_sensor_binary_sensor_proto_rawDescData
}

var file_proto_v1_binary_sensor_binary_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_binary_sensor_binary_sensor_proto_goTypes = []any{
	(*BinarySensorEvent)(nil), // 0: iot.v1.binary_sensor.BinarySensorEvent
	(common.BinaryState)(0),   // 1: iot.v1.common.BinaryState
}
var file_proto_v1_binary_sensor_binary_sensor_proto_depIdxs = []int32{
	1, // 0: iot.v1.binary_sensor.BinarySensorEvent.state:type_name -> iot.v1.common.BinaryState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_binary_sensor_binary_sensor_proto_init() }
func file_proto_v1_binary_sensor_binary_sensor_proto_init() {
	if File_proto_v1_binary_sensor_binary_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_binary_sensor_binary_sensor_proto_rawDesc), len(file_proto_v1_binary_sensor_binary_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_binary_sensor_binary_sensor_proto_goTypes,
		DependencyIndexes: file_proto_v1_binary_sensor_binary_sensor_proto_depIdxs,
		MessageInfos:      file_proto_v1_binary_sensor_binary_sensor_proto_msgTypes,
	}.Build()
	File_proto_v1_binary_sensor_binary_sensor_proto = out.File
	file_proto_v1_binary_sensor_binary_sensor_proto_goTypes = nil
	file_proto_v1_binary_sensor_binary_sensor_proto_depIdxs = nil
}
